site_name: PyxDI
site_description: Dependence Injection library
site_author: Anton Ruhlov
site_url: https://github.com/antonrh/pyxdi

theme:
  name: material
  palette:
    scheme: default
    primary: green

repo_name: antonrh/pyxdi
repo_url: https://github.com/antonrh/pyxdi
edit_uri: ""

nav:
  - Introduction: index.md
  - Usage: usage.md
  - Examples:
      - Basic: examples/basic.md
      - Flask: examples/flask.md
      - Flask + SQLAlchemy: examples/flask_sqlalchemy.md
      - FastAPI: examples/fastapi.md
      - FastAPI + SQLAlchemy: examples/fastapi_sqlalchemy.md
      - Django: examples/django.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
