[tool.poetry]
name = "pyxdi"
version = "0.1.0"
description = ""
authors = ["Anton Ruhlov <antonruhlov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
venusian = "^3.0.0"
anyio = "^3.6.2"
asgiref = "^3.6.0"

[tool.poetry.dev-dependencies]
black = "^23.1.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
flake8-tidy-imports = "^4.8.0"
mypy = "^1.0"
Flask = "^2.2.2"
fastapi = "^0.89.1"
uvicorn = "^0.20.0"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"
combine_as_imports = true

[tool.mypy]
python_version = "3.10"
strict = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
