name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Code quality
    runs-on: ubuntu-latest
    needs: [ cancel-build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Cache poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.3.2
      - uses: snok/install-poetry@v1.3.3
        with:
          version: 1.3.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - name: Install dependencies
      - run: poetry install --no-interaction
      - name: Imports sorting
        run: poetry run isort --check pyxdi/ tests/
      - name: Code formatting
        run: poetry run black --check pyxdi/ tests/
      - name: Code style
        run: poetry run flake8 pyxdi/ tests/
      - name: Static type checking
        run: poetry run mypy pyxdi/ tests/
